### PR TITLE
Initial support for Forward Rendering

### PR DESCRIPTION
**Pull request by bmourit**
I have tested on URP 12, but this needs tested still for URP 13.

### CODE REVIEW

**Comment by Zallist** [comment]
Surprised kPipelineTag didn't need to be updated.
Will check on 2022 in a couple hours / tomorrow.

**Comment by Zallist** [comment]
I merged it knowing it was broken, but fixed the issues that I saw in commit c1903fe680d327d388c5a63e4a67988a3dc1e587.

**Comment by Zallist** [comment]
I'd recommend checking out the latest main branch and seeing if that _still_ works in 2021, but it should since I didn't change anything major. Just reusing the available properties on surface.

**Comment by bmourit** [comment]
> I'd recommend checking out the latest main branch and seeing if that _still_ works in 2021, but it should since I didn't change anything major. Just reusing the available properties on surface.

Just a note that it still works in 2021.

**Pull request merged**
